RisaWeb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('app1.urls')),
    path('admin/', admin.site.urls),
]

app1/urls.py
from django.contrib import admin
from django.urls import path
from app1 import views
app_name='app1'

urlpatterns = [
    path('',views.index,name="index"),
    path('purchase/',views.access,name="purchase"),
    path('admin/', admin.site.urls),
]

app1/models.py
from django.db import models

# Create your models here.
class creditcard(models.Model):
    Name=models.CharField(max_length=250)
    Email=models.EmailField()
    CardNumber=models.IntegerField()
    SecurityNumber=models.IntegerField()
    Zipcode=models.IntegerField()

class accesscodes(models.Model):
    CodeNumber=models.IntegerField()
    id=models.IntegerField(unique=True,primary_key=True)

app1/forms.py
from django import forms
from app1.models import creditcard
from django.core import validators
class creditforms(forms.ModelForm):
    class Meta():
        model=creditcard
        fields="__all__"
    botcatcher=forms.CharField(required=False,widget=forms.HiddenInput,validators=[validators.MaxLengthValidator(0)])

app1/views.py
from django.shortcuts import render
from app1.models import accesscodes,creditcard
from app1 import forms
# Create your views here.
def index(request):
    return render(request,'app1/index.html')


def access(request):
    try:
        model=accesscodes.objects.order_by('id')[0]
        if request.GET.get('sub') == 'Click':
            var1=[model]
        else:
            var1=[]
    except:
        var1=[]
    try:
        var1= var1[0].CodeNumber

    except:
        var1="no codes"
    dict={'model':var1}
    print(var1)
    try:
        model.delete()
    except:
        pass
    return render(request,'app1/purchase.html',context=dict)

templates/app1/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>index</title>
    <link rel="icon" href="{% static "images/Kenpachi_Zaraki.jpg" %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href=" {% static "css/style.css" %}  ">
  </head>
  <body>
    <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">
          Welcome
        </a>
      </div>
      <ul class= "nav navbar-nav">
        <li><a href="{% url "app1:index" %}" >Home</a></li>
        <li><a href="{% url "app1:purchase" %}" >Purchase</a></li>
        <li><a href="{% url "admin:index" %}" >Admin</a></li>
      </ul>
    </div>
  </nav>
    <div id=two class="jumbotron" src=" {% static "images/naruto.jpg" %}  ">

      <h1>VirTUAL bOOkS!</h1>

    </div>
    {% block body_block %}
    <div class="container" id=k>
      <h2>From the Creator</h2>
      <div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src=" {% static "images/1509070512655.jpg" %} " >
      <div class="caption">
        <p>My name is Samuel Okei Oghenetega and I am the author of this small wesite.
        I think the opportunity to make this was amazing irrespective of the time frame and the difficulties associated
        I am especially appreciative of risa as an organization and I am happy that they allowed the start od this program
        Thank you</p>

      </div>
    </div>
  </div>
</div>
<div class="row">
  <h2>About Website</h2>
  <p class="p">The idea behind this website is the purchase of acces codes.
    Its is a small two page website that prints an acces code for the next user when asked for.
    It was created with the Django interface and Html Css and Javascript on the front end.
    This is incomplete as a result of lack of time. </p>

</div>
</div>
<p ><a id=c class="btn btn-lg" href="{% url "app1:purchase" %}" role="button">Click here to get acces codes</a></p>
{% endblock %}
<div class="jumbotron">
<h3>Contact information</h3>
  <ul>
    <li>email:okeisam@yahoo.com, samuel.o.okei@ttu.edu</li>
    <li>linkedin:https://www.linkedin.com/in/samuel-okei-123237156/</li>
    <li>github:https://github.com/Tegasaur</li>
  </ul>
</div>
  </body>
</html>

templates/app1/purchase.html
{% extends "app1/index.html" %}
{% block body_block %}
<h2 id=b > Click Here To Get AccESs CodES </h2>
<form method='GET'>
  <input type="submit" class="btn btn-lg success" value="Click" name='sub'/>
  <p id=a>{{model}}</p>
</form>
{% endblock %}